config/routes.rb
Rails.application.routes.draw do
  resources :photos
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'businesses#index'
  resources :businesses
  resources :services
  resources :hours
  resources :types
  resources :days
  resources :profiles, only: [:show]
  # get '/profile/:id', to: 'profiles#show'
  get '*path' => redirect('/')
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  include BusinessesHelper

  # GET /businesses
  # GET /businesses.json
  def index
    @businesses = Business.where(active: true).distinct.left_joins(:photo).includes(:photo).order(:name)
    @paginate_business = Kaminari.paginate_array(@businesses).page(params[:page])
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
    begin
      @business = Business.find(params[:id])
      @services = Service.where(:business => @business)
      @hours = Hour.where('business_id': @business).distinct
      @image = ''
      photo = Photo.where(:business => @business).limit(1)
      if photo.any?
        @image = photo.first.image
      end
    rescue
      redirect_to businesses_url
    end
  end

  # GET /businesses/new
  def new
    redirect_business
    @business = Business.new
  end

  # GET /businesses/1/edit
  def edit
    @business = Business.find(params[:id])
    #redirect_if_not_user_business! @business
    # write minimum code to make test pass
    # to refactor with helper method if possible
    if user_signed_in? && !current_user.admin && !@business.user.eql?(current_user)
      redirect_to root_path
    end
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = Business.new(business_params)
    @business.user = current_user

    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: 'Business was successfully created.' }
        format.json { render :show, status: :created, location: @business }
      else
        format.html { render :new }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesses/1
  # PATCH/PUT /businesses/1.json
  def update
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { render :show, status: :ok, location: @business }
      else
        format.html { render :edit }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to businesses_url, notice: 'Business was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business
      begin
        @business = Business.find(params[:id])
      rescue
        redirect_to businesses_url
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_params
      params.require(:business).permit(:name, :description, :active, :address1, :address2, :zipcode, :phone_no, :mobile_no, :email, :fax, :type_id)
    end
end

app/helpers/businesses_helper.rb
module BusinessesHelper

  def get_user_business
    Business.where(user_id: current_user)
  end

  def is_user_business?(business)
    if user_signed_in?
      business == get_user_business.first
    else
      false
    end
  end

  def user_has_business?
    !get_user_business.first.nil?
  end

  def redirect_business
    if !current_user.admin and user_has_business?
      redirect_to businesses_url
    end
  end

  def businesses_exist?
    Business.count > 0
  end


  def is_current_user_admin?
    if user_signed_in?
      if current_user.admin.nil?
        false
      else
        current_user.admin
      end
    end
  end

  def is_business_active?(business)
    Business.active
  end

  def redirect_if_business_not_active(business)
    if !is_business_active
      redirect_business
    end
  end

  def redirect_root_if_no_business!
    if user_signed_in? && !is_current_user_admin? && !user_has_business?
      redirect_to root_path
    end
  end

  def redirect_if_not_user_business!(business)
    if user_signed_in? && !current_user.admin && !business.user.eql?(current_user)
      redirect_to root_path
    end
  end

  def redirect_if_not_admin!
    if !is_current_user_admin?
      redirect_to root_path
    end
  end

end

app/views/businesses/_form.html.erb
<%= form_with(model: business, local: true) do |form| %>
  <% if business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
        <% business.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">  
    <div class="form-wrapper col-xs-12 col-md-12 text-center">

      <div class="form-group field">
        <%= form.label :name %>
        <%= form.text_field :name, id: :business_name, class: 'form-control' %>
      </div>

      <div class="form-group field">
        <%= form.label :description %>
        <%= form.text_area :description, id: :business_description, class: 'form-control' %>
      </div>

      <% if is_current_user_admin? %>

        <div class="form-check field">
          <%= form.check_box :active %>
          <%= form.label :active, for: 'active-field' %>
        </div>

      <% end %>


      <div class="form-group field">
        <%= form.label :address1 %>
        <%= form.text_area :address1, id: :business_address1, class: 'form-control' %>
      </div>

      <div class="form-group field">
        <%= form.label :address2 %>
        <%= form.text_area :address2, id: :business_address2, class: 'form-control' %>
      </div>

      <div class="form-group field">
        <%= form.label :zipcode %>
        <%= form.number_field :zipcode, id: :business_zipcode, class: 'form-control' %>
      </div>

      <div class="form-group field">
        <%= form.label :phone_no %>
        <%= form.number_field :phone_no, id: :business_phone_no, class: 'form-control' %>
      </div>

      <div class="form-group field">
        <%= form.label :mobile_no %>
        <%= form.number_field :mobile_no, id: :business_mobile_no, class: 'form-control' %>
      </div>

      <div class="form-group field">
        <%= form.label :email %>
        <%= form.text_field :email, id: :business_email, class: 'form-control' %>
      </div>

      <div class="form-group field">
        <%= form.label :fax %>
        <%= form.number_field :fax, id: :business_fax, class: 'form-control' %>
      </div>

      <div id="business_type" class="form-group field">
        <%= form.label :type_id %>
        <%= form.select :type_id, options_for_select(Type.all.map{|s|[s.name, s.id]}, {class: 'form-control'}) %>
      </div>

      <% if is_current_user_admin? %>

        <div id="business_user" class="form-group field">
          <%= form.label :user_id %>
          <%= form.select :user_id, options_for_select(User.all.map{|u|[u.email, u.id]}, {class: 'form-control'}) %>
        </div>

      <% end %>

      <div class="actions">
        <%= form.submit :Submit, class: "btn btn-block btn-success" %>
      </div>
    <% end %>
    </div>
  </div>

app/views/businesses/edit.html.erb
<h1>Editing Business</h1>

<%= render 'form', business: @business %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.erb
<p id="notice"><%= notice %></p>

<h4 class="lead pt-2">List Of Hair Salons / Stylists / Barbers</h4>

<div class="album py-5">
  <div class="row">

    <% if @businesses.length == 0 %>
      <div class="lead">
        No businesses created yet!
        <%#= link_to_if user_signed_in?, new_business_path, 'Create One.' %>
        <%#= link_to_if !user_signed_in?, new_user_registration_path, 'Create One.' %>
      </div>
    <% end %>

    <% @businesses.each do |business| %>
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          <% if !business.photo.any? %>
            <img class="card-img-top img-fluid card-placeholder-size z-depth-1-half" src="http://via.placeholder.com/300x300?text=Add+Photo" alt="Card image cap">
          <% else %>
            <%= image_tag(business.photo.first.image, class: 'card-img-top img-fluid card-placeholder-size z-depth-1-half') %>
          <% end %>
          <div class="card-body">
            <div class="card-title"><%= business.name %></div>
            <p class="card-text"><%= business.description && business.description.truncate_words(5) %></p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <%= link_to 'Show', business, class: 'btn btn-sm btn-indigo' %>
                <% if business.photo.any? %>
                  <%= link_to 'Photos', profile_path(business), class: 'btn btn-sm btn-deep-purple' %>
                <% end %>
                <% if is_user_business? business or is_current_user_admin? %>
                  <%= link_to "Edit", edit_business_path(business), class: 'btn btn-sm btn-purple' %>
                <% end %>
              </div>
              <small class="text-muted"><%= business.address1.truncate_words(2) %></small>
            </div>
          </div>
        </div>
      </div>
    <% end %>

  </div>
  <% if (user_signed_in? && !user_has_business?) or is_current_user_admin? %>
    <%= link_to 'New Business', new_business_path, class: 'btn btn-sm btn-rounded btn-elegant' %>
  <% end %>

  <% if @businesses.length > 0 %>
    <%= paginate @paginate_business %>
  <% end %>

</div>

app/views/businesses/new.html.erb
<h1>New Business</h1>

<%= render 'form', business: @business %>

<%= link_to 'Back', businesses_path %>

app/views/businesses/show.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron z-depth-1-half" style="background-image: url(<%= @image %>); background-size: cover;">
  <h1 class="display-3"> &nbsp; </h1>
  <% if @image.blank? %>
    <h1 class="display-4">Upload Photo</h1>
  <% end %>
  <h6> &nbsp; </h6>
</div>

<h1 class="mt-4 mb-3"><%= @business.name %>
  <small class="lead"><%= @business.description %></small>
</h1>

<div class="p-3">
  <%= link_to 'Photo Showcase', profile_path(@business), class: "btn btn-elegant btn-rounded" %>
</div>

<div class="show-wrapper">

  <div class="row">
    <div class="col-lg-4 mb-4">
      <div class="card h-100">
        <h5 class="card-header">Details</h5>
        <div class="card-body">
          <small class="text-muted">Address </small>
          <span class="h5"><%= @business.address1 %></span>
          <span class="font-italic"><%= @business.address2 %></span>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <small class="text-muted">Zipcode </small>
            <span class="h5"><%= @business.zipcode %></span>
          </li>

          <li class="list-group-item">
            <small class="text-muted">Phone No</small>
            <span class="h5"><%= @business.phone_no %></span>
            <small class="text-muted">Mobile No</small>
            <span class="h5"><%= @business.mobile_no %></span>
          </li>

          <li class="list-group-item">
            <small class="lead">Email</small>
            <span class="h5 font-italic"><%= @business.email %></span>
          </li>

        </ul>
      </div>

    </div>

    <div class="col-lg-4 mb-4">
      <div class="card h-100">
        <h5 class="card-header">Services</h5>
        <ul class="list-group list-group-flush">
          <% @services.each do |service| %>
            <li class="list-group-item">
              <span class="lead"><%= service.name %></span>
              <% if service.price.present? %>
                <span class="font-italic"> Rs <%= service.price.round  %> </span>
              <% else %>
                <span class="font-italic"></span>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>

    <div class="col-lg-4 mb-4">
      <div class="card h-100">
        <h5 class="card-header">Working Hours</h5>
        <ul class="list-group list-group-flush">
          <% @hours.each do |hour| %>
            <li class="list-group-item">
              <span class="lead"><%= hour.day.name %></span>
              <span class="font-italic"><%= formatTime hour.time_start %></span>
              <span class="font-italic"><%= formatTime hour.time_end %></span>
            </li>
          <% end %>
        </ul>
      </div>
    </div>

  </div>

  <% if is_user_business?(@business) %>
    <%= link_to 'Edit', edit_business_path(@business), class: "btn btn-sm btn-purple btn-rounded" %> |
  <% end %>
  <%= link_to 'Back', businesses_path, class: "btn btn-sm btn-rounded deep-purple darken-4" %>
</div>