config/routes.rb
Rails.application.routes.draw do
  resources :photos
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'businesses#index'
  resources :businesses
  resources :services
  resources :hours
  resources :types
  resources :days
  resources :profiles, only: [:show]
  # get '/profile/:id', to: 'profiles#show'
  get '*path' => redirect('/')
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  include BusinessesHelper
  before_action :redirect_if_not_admin!

  # GET /types
  # GET /types.json
  def index
    @types = Type.all
  end

  # GET /types/1
  # GET /types/1.json
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Type was successfully created.' }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1
  # PATCH/PUT /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url, notice: 'Type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_params
      params.require(:type).permit(:name, :description)
    end
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/types/_form.html.erb
<%= form_with(model: type, local: true) do |form| %>
  <% if type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="form-wrapper col-xs-12 col-md-12 text-center">

      <div class="field form-group">
        <%= form.label :name %>
        <%= form.text_field :name, id: :type_name, class: 'form-control' %>
      </div>

      <div class="field form-group">
        <%= form.label :description %>
        <%= form.text_area :description, id: :type_description, class: 'form-control' %>
      </div>

      <div class="actions">
        <%= form.submit :Submit, class: "btn btn-block btn-success" %>
      </div>

    </div>
  </div>

<% end %>

app/views/types/edit.html.erb
<h1>Editing Type</h1>

<%= render 'form', type: @type %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Types</h1>

<div class="table-responsive-sm">
  <table class="table table-hover">
    <thead class="thead mdb-color darken-3">
      <tr class="text-white">
        <th>Name</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @types.each do |type| %>
        <tr>
          <td><%= type.name %></td>
          <td><%= type.description %></td>
          <td><%= link_to 'Show', type %></td>
          <td><%= link_to 'Edit', edit_type_path(type) %></td>
          <td><%= link_to 'Destroy', type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New Type', new_type_path %>

app/views/types/new.html.erb
<h1>New Type</h1>

<%= render 'form', type: @type %>

<%= link_to 'Back', types_path %>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <span class="lead"><%= @type.name %></span>
</p>

<p>
  <strong>Description:</strong>
  <span class="lead"><%= @type.description %></span>
</p>

<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>