config/routes.rb
Rails.application.routes.draw do
  resources :photos
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'businesses#index'
  resources :businesses
  resources :services
  resources :hours
  resources :types
  resources :days
  resources :profiles, only: [:show]
  # get '/profile/:id', to: 'profiles#show'
  get '*path' => redirect('/')
end

app/models/day.rb
class Day < ApplicationRecord
  has_many :hours
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :set_day, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  include BusinessesHelper
  before_action :redirect_if_not_admin!

  # GET /days
  # GET /days.json
  def index
    @days = Day.all
  end

  # GET /days/1
  # GET /days/1.json
  def show
  end

  # GET /days/new
  def new
    @day = Day.new
  end

  # GET /days/1/edit
  def edit
  end

  # POST /days
  # POST /days.json
  def create
    @day = Day.new(day_params)

    respond_to do |format|
      if @day.save
        format.html { redirect_to @day, notice: 'Day was successfully created.' }
        format.json { render :show, status: :created, location: @day }
      else
        format.html { render :new }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /days/1
  # PATCH/PUT /days/1.json
  def update
    respond_to do |format|
      if @day.update(day_params)
        format.html { redirect_to @day, notice: 'Day was successfully updated.' }
        format.json { render :show, status: :ok, location: @day }
      else
        format.html { render :edit }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /days/1
  # DELETE /days/1.json
  def destroy
    @day.destroy
    respond_to do |format|
      format.html { redirect_to days_url, notice: 'Day was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_day
      @day = Day.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def day_params
      params.require(:day).permit(:name)
    end
end

app/helpers/days_helper.rb
module DaysHelper
end

app/views/days/_form.html.erb
<%= form_with(model: day, local: true) do |form| %>
  <% if day.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(day.errors.count, "error") %> prohibited this day from being saved:</h2>

      <ul>
      <% day.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :day_name, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit :Submit, class: "btn btn-block btn-success" %>
  </div>
<% end %>

app/views/days/edit.html.erb
<h1>Editing Day</h1>

<%= render 'form', day: @day %>

<%= link_to 'Show', @day %> |
<%= link_to 'Back', days_path %>

app/views/days/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Days</h1>

<div class="table-responsive-sm">
  <table class="table table-hover">
    <thead class="thead mdb-color darken-3">
      <tr class="text-white">
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @days.each do |day| %>
      <tr>
        <td><%= day.name %></td>
        <td><%= link_to 'Show', day %></td>
        <td><%= link_to 'Edit', edit_day_path(day) %></td>
        <td><%= link_to 'Destroy', day, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New Day', new_day_path %>

app/views/days/new.html.erb
<h1>New Day</h1>

<%= render 'form', day: @day %>

<%= link_to 'Back', days_path %>

app/views/days/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <span class="lead"><%= @day.name %></span>
</p>

<%= link_to 'Edit', edit_day_path(@day) %> |
<%= link_to 'Back', days_path %>