config/routes.rb
Rails.application.routes.draw do
  resources :photos
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'businesses#index'
  resources :businesses
  resources :services
  resources :hours
  resources :types
  resources :days
  resources :profiles, only: [:show]
  # get '/profile/:id', to: 'profiles#show'
  get '*path' => redirect('/')
end

app/views/layouts/_footer.html.erb
<footer class="footer py-1 bg-dark">
	<div class="container">
		<p class="m-0 text-center text-white">Copyright &copy; DLS 2018</p>
	</div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
	<div class="container">
    <a class="py-2" href="/">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="d-block mx-auto"><circle cx="12" cy="12" r="10"></circle><line x1="14.31" y1="8" x2="20.05" y2="17.94"></line><line x1="9.69" y1="8" x2="21.17" y2="8"></line><line x1="7.38" y1="12" x2="13.12" y2="2.06"></line><line x1="9.69" y1="16" x2="3.95" y2="6.06"></line><line x1="14.31" y1="16" x2="2.83" y2="16"></line><line x1="16.62" y1="12" x2="10.88" y2="21.94"></line></svg>
    </a>
		<div class="px-3"><%= link_to "Hair Styling Salons", businesses_path, class: "navbar-brand" %></div>
		<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarResponsive">
			<ul class="navbar-nav ml-auto">
				<%= active_link_to "Businesses", businesses_path, class: "nav-item nav-link" %>
				<% if user_signed_in? and user_has_business? or is_current_user_admin? %>
					<%= active_link_to "Services", services_path, class: "nav-item nav-link" %>
					<%= active_link_to "Working Hours", hours_path, class: "nav-item nav-link" %>
					<%= active_link_to "Photos", photos_path, class: "nav-item nav-link" %>
          <% if is_current_user_admin? %>
					  <%= active_link_to "Types", types_path, class: "nav-item nav-link" %>
					  <%= active_link_to "Days", days_path, class: "nav-item nav-link" %>
          <% end %>
				<% end  %>
			<div class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>
					<%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-item nav-link sign-out-button" %>

					<div class="navbar-user-container d-flex h-100">
						<div class="navbar-user nav-item row justify-content-center align-self-center "> <%= current_user.email %> </div>
					</div>
				<% else %>
					<%= link_to "For Professionals", new_user_session_path, class: "nav-item nav-link" %>
				<% end %>
			</div>
		</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StylingApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-120618956-1 "></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'UA-120618956-1');
    </script>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container text-center">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>